Models/Job.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace Job_Offers_Website.Models
{
    public class Job
    {
        public int Id { get; set; }
        [DisplayName("Post Name")]
        public string JobTitle { get; set; }
        [DisplayName("Post description")]
        [AllowHtml]
        public string JobContent { get; set; }
        [DisplayName("Image ")]
        public string JobImage { get; set; }
        [DisplayName("JobBudget ")]
        public string JobBudget { get; set; }

        [DisplayName("Post Category")]
        public int CategoryId { get; set; }

        public string UserID { get; set; }
        [DisplayName("New Post")]
        public string ACtive { get; set; }

        public virtual Category Category { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}

Models/JobsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Job_Offers_Website.Models
{
    public class JobsViewModel
    {
        public string JobTitle { get; set; }
        public IEnumerable<ApplyForJob> Items { get; set; }
    }
}

Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Job_Offers_Website.Models;
using WebApplication1.Models;
using System.IO;
using Microsoft.AspNet.Identity;

namespace Job_Offers_Website.Controllers
{
    [Authorize]
    public class JobsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Jobs
     
        public ActionResult Index()
        {
            var jobs = db.Jobs.Include(j => j.Category);
            return View(jobs.ToList()); 
        }


       
        public ActionResult RequestPost()
        {
            var jobs = db.Jobs.Include(j => j.Category);
            return View(jobs.Where( a=>a.ACtive.Contains("1")).ToList());
        }

        public ActionResult Mypost()
        {
            var UserId = User.Identity.GetUserId();
            var Jobs = db.Jobs.Where(a => a.UserID == UserId);
            return View(Jobs.ToList());
        }



     
        // GET: Jobs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // GET: Jobs/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName");
            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Job job, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                upload.SaveAs(path);
                job.JobImage = upload.FileName;
                job.UserID = User.Identity.GetUserId();
                db.Jobs.Add(job);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName", job.CategoryId);
            return View(job);
        }

        // GET: Jobs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName", job.CategoryId);
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Job job, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string oldPath = Path.Combine(Server.MapPath("~/Uploads"), job.JobImage);

                if (upload != null)
                {
                    System.IO.File.Delete(oldPath);
                    string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                    upload.SaveAs(path);
                    job.JobImage = upload.FileName;
                }

                
                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName", job.CategoryId);
            return View(job);
        }

        // GET: Jobs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Job job = db.Jobs.Find(id);
            db.Jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Jobs/Create.cshtml
@model Job_Offers_Website.Models.Job

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Create</h2>
<script src="~/Scripts/ckeditor/ckeditor.js"></script>

@using (Html.BeginForm("Create", "Jobs", FormMethod.Post,  new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Job</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.JobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.JobBudget, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.JobBudget, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.JobBudget, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ACtive, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            
            @Html.RadioButtonFor(model => model.ACtive, "0")

            @Html.ValidationMessageFor(model => model.ACtive, "", new { @class = "text-danger" })
        </div>
    </div>




    <div class="form-group">
        @Html.LabelFor(model => model.JobContent, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.JobContent, new { htmlAttributes = new { @class = "form-control", @id = "JobContent" } })
            @Html.ValidationMessageFor(model => model.JobContent, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.JobImage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="upload" />
            @Html.ValidationMessageFor(model => model.JobImage, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, "Type Category", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    CKEDITOR.replace("JobContent");
</script>

Views/Jobs/Delete.cshtml
@model Job_Offers_Website.Models.Job

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>delete Post</h2>

<h3>Are you sure to delete the Post?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobImage)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model=>model.JobImage)"
                 class="thumbnail"
                 style="width:48px; height:48px;" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Confirm" class="btn btn-danger" /> |
            @Html.ActionLink("Back to posts", "Index")
        </div>
    }
</div>

Views/Jobs/Details.cshtml
@model Job_Offers_Website.Models.Job

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Job</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.JobContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobBudget)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.JobBudget)
        </dt>



        <dd>
            @Html.Raw(HttpUtility.HtmlDecode(Html.DisplayFor(model => model.JobContent).ToString()))

        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobImage)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model=>model.JobImage)"
                 class="thumbnail"
                 style="width:48px; height:48px;" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Jobs/Edit.cshtml
@model Job_Offers_Website.Models.Job

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Jobs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <div class="alert alert-danger" id="error-div" style="display:none">
            <span id="view-err">

            </span>
        </div>




        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.JobImage)

        <div class="form-group">
            @Html.LabelFor(model => model.JobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="upload" id="myImage" />
                @Html.ValidationMessageFor(model => model.JobImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" id="save" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section scripts{
    <script>
    $(function () {
        $("#save").click(function () {
           
            //Check if the input is Empty
            //if ($("#JobImage").val() == "") {
            //    $("#error-div").fadeIn();
            //    $("#view-err").append("Choose Photo");
            //    return false;
            //}

            if ($("#myImage").val() != "") {
            //Check if the Image extension is valid
                var filename = document.getElementById("myImage").value;
            var extensionImg = filename.substr(filename.lastIndexOf('.') + 1);
            var validExtensions = ['jpg', 'png', 'gif', 'bmp'];
            if ($.inArray(extensionImg, validExtensions) == -1) {
                $("#error-div").fadeIn();
                $("#view-err").append("Please choose an image with the correct extension");
                return false;
            }

            //Check if the Image Size is valid (2 mb)
            var myFileSize = document.getElementById("myImage").files[0].size / 1024 / 1024;

            if (myFileSize > 2) {
                $("#error-div").fadeIn();
                $("#view-err").append("Please choose an image whose size is less than 2MB");
                return false;
            }
            }
        });
    });
</script>
    
    }

Views/Jobs/Index.cshtml
@model IEnumerable<Job_Offers_Website.Models.Job>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2 class="text-left">POSts Job</h2>

<p class="text-left">
    @Html.ActionLink("Create new Post", "Create")
</p>
<div class="table-responsive">
    <table class="table">
        <tr class="text-left">
            <th class="text-left">
                @Html.Label("Manage")
            </th>
            <th class="text-left">
                @Html.DisplayNameFor(model => model.JobImage)
            </th>
            <th class="text-left">
                @Html.DisplayNameFor(model => model.JobContent)
            </th>
            <th class="text-left">
                @Html.DisplayNameFor(model => model.JobTitle)
            </th>
            <th class="text-left">
                @Html.DisplayNameFor(model => model.Category.CategoryName)
            </th>



        </tr>

        @foreach (var item in Model)
        {
    <tr class="text-left">
        <td class="text-left">
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
        <td class="text-left">
            <img src="~/Uploads/@Html.DisplayFor(model=>item.JobImage)"
                 class="thumbnail" style="width:48px; height:48px" />
        </td>
        <td class="text-left">
            @Html.DisplayFor(modelItem => item.JobContent)
        </td>
        <td class="text-left">
            @Html.DisplayFor(modelItem => item.JobTitle)
        </td>
        <td class="text-left">
            @Html.DisplayFor(modelItem => item.Category.CategoryName)
        </td>




    </tr>
        }

    </table>
    </div>

Views/Jobs/Mypost.cshtml
 

@model IEnumerable<Job_Offers_Website.Models.Job>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2 class="text-left">POSts Job</h2>

<p class="text-left">
    @Html.ActionLink("Create new Post", "Create")
</p>
<div class="table-responsive">
    <table class="table">
        <tr class="text-left">
            <th class="text-left">
                @Html.Label("Manage")
            </th>
            <th class="text-left">
                @Html.DisplayNameFor(model => model.JobImage)
            </th>
            <th class="text-left">
                @Html.DisplayNameFor(model => model.JobContent)
            </th>
            <th class="text-left">
                @Html.DisplayNameFor(model => model.JobTitle)
            </th>
            <th class="text-left">
                @Html.DisplayNameFor(model => model.Category.CategoryName)
            </th>



        </tr>

        @foreach (var item in Model)
        {
            <tr class="text-left">
                <td class="text-left">
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
                <td class="text-left">
                    <img src="~/Uploads/@Html.DisplayFor(model=>item.JobImage)"
                         class="thumbnail" style="width:48px; height:48px" />
                </td>
                <td class="text-left">
                    @Html.DisplayFor(modelItem => item.JobContent)
                </td>
                <td class="text-left">
                    @Html.DisplayFor(modelItem => item.JobTitle)
                </td>
                <td class="text-left">
                    @Html.DisplayFor(modelItem => item.Category.CategoryName)
                </td>




            </tr>
        }

    </table>
</div>

Views/Jobs/RequestPost.cshtml
@model IEnumerable<Job_Offers_Website.Models.Job>

@{
    ViewBag.Title = "RequestPost";
}

<h2>RequestPost</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.JobTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobContent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobImage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ACtive)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.JobTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobContent)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobImage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ACtive)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>